Add windows_file.template operation
Fizzadar/pyinfra pull request #651
Opened 2021-08-23 15:23 UTC by timeisapear

Mostly copy/pasted from file.template. One tweak is making the IO buffer-type bytes since
winrm connector _put_file expects a bytes input. Therefore output_file was changed from:

```
output_file = six.StringIO(output)
```
 to

```
output_file = six.BytesIO(six.ensure_binary(output))
```

References https://github.com/Fizzadar/pyinfra/issues/645

I have not added tests yet but may be able to add them later.

2021-09-07 08:58 UTC, Fizzadar requested changes
Hi @timeisapear - thank you for adding this, looks great overall. Once minor comment and the tests - I'm happy to add tests after merging for this if you'd like me to?

2021-09-07 08:58 UTC, Fizzadar commented on pyinfra/operations/windows_files.py
> +        files.template(
These examples need to be `windows_files.templates`.

2024-01-13 10:08 UTC, Fizzadar commented
v3 will remove Windows support (into a separate package, https://github.com/pyinfra-dev/pyinfra-windows. Once that's released I shall move this over and close this PR.

2025-08-08 12:50 UTC, Nicoretti commented
This PR also seems to be dead.

2025-12-08 17:56 UTC, Fizzadar commented
Killing this, FYI @rod7760 might be something worth pulling into pyinfra-windows maybe not!

2025-12-08 17:56 UTC, closed without merging